version: 2
general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore

jobs:
  build:
    docker:
      - image: humhei/dotnet-mono
    steps:
      - checkout
      - run:
          name: run-tests
          command: |
            chmod 755 ./*.sh
            export TERM=xterm-256color
            ./fake.sh build -t RunCI